const teclas = [
  [
    { label: ['"', '\''], tecla: 192, dedo: 'indicador direito' },
    { label: ['!', '1'], tecla: 49, dedo: 'indicador direito' },
    { label: ['@', '2'], tecla: 50, dedo: 'indicador direito' },
    { label: ['#', '3'], tecla: 51, dedo: 'indicador direito' },
    { label: ['$', '4'], tecla: 52, dedo: 'indicador direito' },
    { label: ['%', '5'], tecla: 53, dedo: 'indicador direito' },
    { label: ['¨', '6'], tecla: 54, dedo: 'indicador direito' },
    { label: ['&', '7'], tecla: 55, dedo: 'indicador direito' },
    { label: ['*', '8'], tecla: 56, dedo: 'indicador direito' },
    { label: ['(', '9'], tecla: 57, dedo: 'indicador direito' },
    { label: [')', '0'], tecla: 48, dedo: 'indicador direito' },
    { label: ['_', '-'], tecla: 189, dedo: 'indicador direito' },
    { label: ['+', '='], tecla: 187, dedo: 'indicador direito' },
    { label: ['}', ']'], tecla: 220, dedo: 'indicador direito' },
    { label: ['Backspace'], tecla: 8, classe: 'backspace', dedo: 'indicador direito' },
  ],
  [
    { label: ['Tab'], tecla: 9, classe: 'tab', dedo: 'mínimo esquerdo' },
    { label: ['Q'], tecla: 81, dedo: 'mínimo esquerdo' },
    { label: ['W'], tecla: 87, dedo: 'anelar esquerdo' },
    { label: ['E'], tecla: 69, dedo: 'médio esquerdo' },
    { label: ['R'], tecla: 82, dedo: 'indicador esquerdo' },
    { label: ['T'], tecla: 84, dedo: 'indicador esquerdo' },
    { label: ['Y'], tecla: 89, dedo: 'indicador direito' },
    { label: ['U'], tecla: 85, dedo: 'indicador direito' },
    { label: ['I'], tecla: 73, dedo: 'médio direito' },
    { label: ['O'], tecla: 79, dedo: 'anelar direito' },
    { label: ['P'], tecla: 80, dedo: 'mínimo direito' },
    { label: ['`', '´'], tecla: 219, dedo: 'indicador direito' },
    { label: ['{', '['], tecla: 221, style: 'width: 116px', dedo: 'indicador direito' },
  ],
  [
    { label: ['Capslock'], tecla: 20, classe: 'caps', dedo: 'mínimo esquerdo' },
    { label: ['A'], tecla: 65, dedo: 'mínimo esquerdo' },
    { label: ['S'], tecla: 83, dedo: 'anelar esquerdo' },
    { label: ['D'], tecla: 68, dedo: 'médio esquerdo' },
    { label: ['F'], tecla: 70, dedo: 'indicador esquerdo' },
    { label: ['G'], tecla: 71, dedo: 'indicador esquerdo' },
    { label: ['H'], tecla: 72, dedo: 'indicador direito' },
    { label: ['J'], tecla: 74, dedo: 'indicador direito' },
    { label: ['K'], tecla: 75, dedo: 'médio direito' },
    { label: ['L'], tecla: 76, dedo: 'anelar direito' },
    { label: ['Ç'], tecla: 186, dedo: 'mínimo direito' },
    { label: ['^', '~'], tecla: 222, dedo: 'indicador direito' },
    { label: ['Enter'], tecla: 13, classe: 'enter', dedo: 'indicador direito' },
  ],
  [
    { label: ['Shift'], tecla: 16, classe: 'shift', dedo: 'mínimo esquerdo' },
    { label: ['|', '\\'], tecla: 220, dedo: 'mínimo esquerdo' },
    { label: ['Z'], tecla: 90, dedo: 'anelar esquerdo' },
    { label: ['X'], tecla: 88, dedo: 'médio esquerdo' },
    { label: ['C'], tecla: 67, dedo: 'indicador esquerdo' },
    { label: ['V'], tecla: 86, dedo: 'indicador esquerdo' },
    { label: ['B'], tecla: 66, dedo: 'indicador direito' },
    { label: ['N'], tecla: 78, dedo: 'indicador direito' },
    { label: ['M'], tecla: 77, dedo: 'médio direito' },
    { label: ['<', ','], tecla: 188, dedo: 'anelar direito' },
    { label: ['>', '.'], tecla: 190, dedo: 'mínimo direito' },
    { label: [':', ';'], tecla: 191, dedo: 'indicador direito' },
    { label: ['?', '/'], tecla: 191, dedo: 'indicador direito' },
    { label: ['Shift'], tecla: 16, classe: 'shift', left: false, dedo: 'indicador direito' },
  ],
  [
    { label: ['Ctrl'], tecla: 17, classe: 'other', dedo: 'mínimo esquerdo' },
    { label: ['Win'], tecla: null, classe: 'other', dedo: 'anelar esquerdo' },
    { label: ['Alt'], tecla: 18, classe: 'other', dedo: 'médio esquerdo' },
    { label: ['Space'], tecla: 32, classe: 'other space', dedo: 'polegar esquerdo' },
    { label: ['Alt Gr'], tecla: 225, classe: 'other', dedo: 'indicador direito' },
    { label: ['Win'], tecla: null, classe: 'other', dedo: 'médio direito' },
    { label: ['Ctrl'], tecla: 17, classe: 'other', left: false, dedo: 'indicador mínimo' },
  ]
]

export default teclas