const teclas = [
  [
    { label: ['"', '\''], tecla: 192, numDedo: 1, dedo: 'indicador direito' },
    { label: ['!', '1'], tecla: 49, numDedo: 1, dedo: 'indicador direito' },
    { label: ['@', '2'], tecla: 50, numDedo: 1, dedo: 'indicador direito' },
    { label: ['#', '3'], tecla: 51, numDedo: 1, dedo: 'indicador direito' },
    { label: ['$', '4'], tecla: 52, numDedo: 1, dedo: 'indicador direito' },
    { label: ['%', '5'], tecla: 53, numDedo: 1, dedo: 'indicador direito' },
    { label: ['¨', '6'], tecla: 54, numDedo: 1, dedo: 'indicador direito' },
    { label: ['&', '7'], tecla: 55, numDedo: 1, dedo: 'indicador direito' },
    { label: ['*', '8'], tecla: 56, numDedo: 1, dedo: 'indicador direito' },
    { label: ['(', '9'], tecla: 57, numDedo: 1, dedo: 'indicador direito' },
    { label: [')', '0'], tecla: 48, numDedo: 1, dedo: 'indicador direito' },
    { label: ['_', '-'], tecla: 189, numDedo: 1, dedo: 'indicador direito' },
    { label: ['+', '='], tecla: 187, numDedo: 1, dedo: 'indicador direito' },
    { label: ['}', ']'], tecla: 220, numDedo: 1, dedo: 'indicador direito' },
    { label: ['Backspace'], tecla: 8, classe: 'backspace', numDedo: 1, dedo: 'indicador direito' },
  ],
  [
    { label: ['Tab'], tecla: 9, classe: 'tab', numDedo: -4, dedo: 'mínimo esquerdo' },
    { label: ['Q'], tecla: 81, numDedo: -4, dedo: 'mínimo esquerdo' },
    { label: ['W'], tecla: 87, numDedo: -3, dedo: 'anelar esquerdo' },
    { label: ['E'], tecla: 69, numDedo: -2, dedo: 'médio esquerdo' },
    { label: ['R'], tecla: 82, numDedo: -1, dedo: 'indicador esquerdo' },
    { label: ['T'], tecla: 84, numDedo: -1, dedo: 'indicador esquerdo' },
    { label: ['Y'], tecla: 89, numDedo: 1, dedo: 'indicador direito' },
    { label: ['U'], tecla: 85, numDedo: 1, dedo: 'indicador direito' },
    { label: ['I'], tecla: 73, numDedo: 2, dedo: 'médio direito' },
    { label: ['O'], tecla: 79, numDedo: 3, dedo: 'anelar direito' },
    { label: ['P'], tecla: 80, numDedo: 4, dedo: 'mínimo direito' },
    { label: ['`', '´'], tecla: 219, numDedo: 1, dedo: 'indicador direito' },
    { label: ['{', '['], tecla: 221, style: 'width: 116px', numDedo: 1, dedo: 'indicador direito' },
  ],
  [
    { label: ['Capslock'], tecla: 20, classe: 'caps', numDedo: -4, dedo: 'mínimo esquerdo' },
    { label: ['A'], tecla: 65, numDedo: -4, dedo: 'mínimo esquerdo' },
    { label: ['S'], tecla: 83, numDedo: -3, dedo: 'anelar esquerdo' },
    { label: ['D'], tecla: 68, numDedo: -2, dedo: 'médio esquerdo' },
    { label: ['F'], tecla: 70, numDedo: -1, dedo: 'indicador esquerdo' },
    { label: ['G'], tecla: 71, numDedo: -1, dedo: 'indicador esquerdo' },
    { label: ['H'], tecla: 72, numDedo: 1, dedo: 'indicador direito' },
    { label: ['J'], tecla: 74, numDedo: 1, dedo: 'indicador direito' },
    { label: ['K'], tecla: 75, numDedo: 2, dedo: 'médio direito' },
    { label: ['L'], tecla: 76, numDedo: 3, dedo: 'anelar direito' },
    { label: ['Ç'], tecla: 186, numDedo: 4, dedo: 'mínimo direito' },
    { label: ['^', '~'], tecla: 222, numDedo: 1, dedo: 'indicador direito' },
    { label: ['Enter'], tecla: 13, classe: 'enter', numDedo: 1, dedo: 'indicador direito' },
  ],
  [
    { label: ['Shift'], tecla: 16, classe: 'shift', numDedo: -4, dedo: 'mínimo esquerdo' },
    { label: ['|', '\\'], tecla: 220, numDedo: -4, dedo: 'mínimo esquerdo' },
    { label: ['Z'], tecla: 90, numDedo: -3, dedo: 'anelar esquerdo' },
    { label: ['X'], tecla: 88, numDedo: -2, dedo: 'médio esquerdo' },
    { label: ['C'], tecla: 67, numDedo: -1, dedo: 'indicador esquerdo' },
    { label: ['V'], tecla: 86, numDedo: -1, dedo: 'indicador esquerdo' },
    { label: ['B'], tecla: 66, numDedo: 1, dedo: 'indicador direito' },
    { label: ['N'], tecla: 78, numDedo: 1, dedo: 'indicador direito' },
    { label: ['M'], tecla: 77, numDedo: 2, dedo: 'médio direito' },
    { label: ['<', ','], tecla: 188, numDedo: 3, dedo: 'anelar direito' },
    { label: ['>', '.'], tecla: 190, numDedo: 4, dedo: 'mínimo direito' },
    { label: [':', ';'], tecla: 191, numDedo: 1, dedo: 'indicador direito' },
    { label: ['?', '/'], tecla: 191, numDedo: 1, dedo: 'indicador direito' },
    { label: ['Shift'], tecla: 16, classe: 'shift', left: false, numDedo: 1, dedo: 'indicador direito' },
  ],
  [
    { label: ['Ctrl'], tecla: 17, classe: 'other', numDedo: -4, dedo: 'mínimo esquerdo' },
    { label: ['Win'], tecla: null, classe: 'other', numDedo: -3, dedo: 'anelar esquerdo' },
    { label: ['Alt'], tecla: 18, classe: 'other', numDedo: -2, dedo: 'médio esquerdo' },
    { label: ['Space'], tecla: 32, classe: 'other space', numDedo: 5, dedo: 'polegar esquerdo' },
    { label: ['Alt Gr'], tecla: 225, classe: 'other', numDedo: 1, dedo: 'indicador direito' },
    { label: ['Win'], tecla: null, classe: 'other', numDedo: 2, dedo: 'médio direito' },
    { label: ['Ctrl'], tecla: 17, classe: 'other', left: false, numDedo: 0, dedo: 'indicador mínimo' },
  ]
]

export default teclas